package pl.eparking.api.aplikacja;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-02-06T20:42:07.428+01:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "ParkingAplikacja_Usluga", 
                  wsdlLocation = "file:/projects/eparking/workspace/eparking/EparkingServiceRepository/src/main/resources/ParkingAplikacja/ParkingAplikacja.wsdl",
                  targetNamespace = "http://eparking.pl/api/aplikacja/") 
public class ParkingAplikacjaUsluga extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://eparking.pl/api/aplikacja/", "ParkingAplikacja_Usluga");
    public final static QName ParkingAplikacjaPort = new QName("http://eparking.pl/api/aplikacja/", "ParkingAplikacja_Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/projects/eparking/workspace/eparking/EparkingServiceRepository/src/main/resources/ParkingAplikacja/ParkingAplikacja.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ParkingAplikacjaUsluga.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/projects/eparking/workspace/eparking/EparkingServiceRepository/src/main/resources/ParkingAplikacja/ParkingAplikacja.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ParkingAplikacjaUsluga(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ParkingAplikacjaUsluga(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ParkingAplikacjaUsluga() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ParkingAplikacjaUsluga(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ParkingAplikacjaUsluga(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ParkingAplikacjaUsluga(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Parking
     */
    @WebEndpoint(name = "ParkingAplikacja_Port")
    public Parking getParkingAplikacjaPort() {
        return super.getPort(ParkingAplikacjaPort, Parking.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Parking
     */
    @WebEndpoint(name = "ParkingAplikacja_Port")
    public Parking getParkingAplikacjaPort(WebServiceFeature... features) {
        return super.getPort(ParkingAplikacjaPort, Parking.class, features);
    }

}
