package pl.eparking.errorhandlerservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-02-06T20:42:07.294+01:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "ErrorHandlerService", 
                  wsdlLocation = "file:/projects/eparking/workspace/eparking/EparkingServiceRepository/src/main/resources/ErrorHandlerService/ErrorHandlerService.wsdl",
                  targetNamespace = "http://eparking.pl/errorhandlerservice") 
public class ErrorHandlerService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://eparking.pl/errorhandlerservice", "ErrorHandlerService");
    public final static QName ErrorHandlerServiceSOAP = new QName("http://eparking.pl/errorhandlerservice", "ErrorHandlerServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/projects/eparking/workspace/eparking/EparkingServiceRepository/src/main/resources/ErrorHandlerService/ErrorHandlerService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ErrorHandlerService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/projects/eparking/workspace/eparking/EparkingServiceRepository/src/main/resources/ErrorHandlerService/ErrorHandlerService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ErrorHandlerService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ErrorHandlerService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ErrorHandlerService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ErrorHandlerService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ErrorHandlerService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ErrorHandlerService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ErrorHandlerService
     */
    @WebEndpoint(name = "ErrorHandlerServiceSOAP")
    public ErrorHandlerService getErrorHandlerServiceSOAP() {
        return super.getPort(ErrorHandlerServiceSOAP, ErrorHandlerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ErrorHandlerService
     */
    @WebEndpoint(name = "ErrorHandlerServiceSOAP")
    public ErrorHandlerService getErrorHandlerServiceSOAP(WebServiceFeature... features) {
        return super.getPort(ErrorHandlerServiceSOAP, ErrorHandlerService.class, features);
    }

}
