package pl.eparking.api.aplikacja;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-02-06T20:44:05.769+01:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://eparking.pl/api/aplikacja/", name = "Parking")
@XmlSeeAlso({ObjectFactory.class})
public interface Parking {

    @WebMethod(operationName = "DodajParking", action = "http://eparking.pl/api/aplikacja/DodajParking")
    @RequestWrapper(localName = "DodajParking", targetNamespace = "http://eparking.pl/api/aplikacja/", className = "pl.eparking.api.aplikacja.DodajParking")
    @ResponseWrapper(localName = "DodajParkingResponse", targetNamespace = "http://eparking.pl/api/aplikacja/", className = "pl.eparking.api.aplikacja.DodajParkingResponse")
    public void dodajParking(
        @WebParam(name = "DodajParkingStart", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar dodajParkingStart,
        @WebParam(name = "DodajParkingKoniec", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar dodajParkingKoniec,
        @WebParam(name = "DodajParkingKonto", targetNamespace = "")
        java.lang.String dodajParkingKonto,
        @WebParam(name = "DodajParkingPojazd", targetNamespace = "")
        java.lang.String dodajParkingPojazd,
        @WebParam(name = "DodajParkingKodPocztowy", targetNamespace = "")
        java.lang.String dodajParkingKodPocztowy,
        @WebParam(name = "DodajParkingMiasto", targetNamespace = "")
        java.lang.String dodajParkingMiasto,
        @WebParam(name = "DodajParkingUlica", targetNamespace = "")
        java.lang.String dodajParkingUlica,
        @WebParam(name = "DodajParkingNumer", targetNamespace = "")
        java.lang.String dodajParkingNumer,
        @WebParam(name = "DodajParkingCzas", targetNamespace = "")
        java.lang.String dodajParkingCzas,
        @WebParam(name = "DodajParkingCena", targetNamespace = "")
        java.lang.String dodajParkingCena,
        @WebParam(name = "DodajParkingSaldoDodatnie", targetNamespace = "")
        boolean dodajParkingSaldoDodatnie,
        @WebParam(mode = WebParam.Mode.OUT, name = "DodajParkingSukces", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> dodajParkingSukces,
        @WebParam(mode = WebParam.Mode.OUT, name = "DodajParkingParking", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> dodajParkingParking
    );

    @WebMethod(operationName = "ModyfikujParking", action = "http://eparking.pl/api/aplikacja/ModyfikujParking")
    @RequestWrapper(localName = "ModyfikujParking", targetNamespace = "http://eparking.pl/api/aplikacja/", className = "pl.eparking.api.aplikacja.ModyfikujParking")
    @ResponseWrapper(localName = "ModyfikujParkingResponse", targetNamespace = "http://eparking.pl/api/aplikacja/", className = "pl.eparking.api.aplikacja.ModyfikujParkingResponse")
    @WebResult(name = "ModyfikujParkingSukces", targetNamespace = "")
    public int modyfikujParking(
        @WebParam(name = "ModyfikujParkingKonto", targetNamespace = "")
        java.lang.String modyfikujParkingKonto,
        @WebParam(name = "ModyfikujParkingParking", targetNamespace = "")
        java.lang.String modyfikujParkingParking,
        @WebParam(name = "ModyfikujParkingPojazd", targetNamespace = "")
        java.lang.String modyfikujParkingPojazd,
        @WebParam(name = "ModyfikujParkingStart", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar modyfikujParkingStart,
        @WebParam(name = "ModyfikujParkingKoniec", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar modyfikujParkingKoniec,
        @WebParam(name = "ModyfikujParkingPoczta", targetNamespace = "")
        java.lang.String modyfikujParkingPoczta,
        @WebParam(name = "ModyfikujParkingMiasto", targetNamespace = "")
        java.lang.String modyfikujParkingMiasto,
        @WebParam(name = "ModyfikujParkingUlica", targetNamespace = "")
        java.lang.String modyfikujParkingUlica,
        @WebParam(name = "ModyfikujParkingNumer", targetNamespace = "")
        java.lang.String modyfikujParkingNumer,
        @WebParam(name = "ModyfikujParkingCzas", targetNamespace = "")
        java.lang.String modyfikujParkingCzas,
        @WebParam(name = "ModyfikujParkingCena", targetNamespace = "")
        java.lang.String modyfikujParkingCena
    );

    @WebMethod(operationName = "DodajMandat", action = "http://eparking.pl/api/aplikacja/DodajMandat")
    @RequestWrapper(localName = "DodajMandat", targetNamespace = "http://eparking.pl/api/aplikacja/", className = "pl.eparking.api.aplikacja.DodajMandat")
    @ResponseWrapper(localName = "DodajMandatResponse", targetNamespace = "http://eparking.pl/api/aplikacja/", className = "pl.eparking.api.aplikacja.DodajMandatResponse")
    public void dodajMandat(
        @WebParam(name = "DodajMandatKwota", targetNamespace = "")
        java.lang.String dodajMandatKwota,
        @WebParam(name = "DodajMandatIdKontroli", targetNamespace = "")
        java.lang.String dodajMandatIdKontroli,
        @WebParam(name = "DodajMandatIdKontaKierowcy", targetNamespace = "")
        java.lang.String dodajMandatIdKontaKierowcy,
        @WebParam(name = "DodajMandatDataKontroli", targetNamespace = "")
        java.lang.String dodajMandatDataKontroli,
        @WebParam(name = "DodajMandatTypMandatu", targetNamespace = "")
        java.lang.String dodajMandatTypMandatu,
        @WebParam(mode = WebParam.Mode.OUT, name = "DodajMandatSukces", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> dodajMandatSukces,
        @WebParam(mode = WebParam.Mode.OUT, name = "DodajMandatIdMandatu", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> dodajMandatIdMandatu
    );

    @WebMethod(operationName = "DodajKontrole", action = "http://eparking.pl/api/aplikacja/DodajKontrole")
    @RequestWrapper(localName = "DodajKontrole", targetNamespace = "http://eparking.pl/api/aplikacja/", className = "pl.eparking.api.aplikacja.DodajKontrole")
    @ResponseWrapper(localName = "DodajKontroleResponse", targetNamespace = "http://eparking.pl/api/aplikacja/", className = "pl.eparking.api.aplikacja.DodajKontroleResponse")
    public void dodajKontrole(
        @WebParam(name = "DodajKontroleData", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar dodajKontroleData,
        @WebParam(name = "DodajKontroleKontroler", targetNamespace = "")
        java.lang.String dodajKontroleKontroler,
        @WebParam(name = "DodajKontroleAdres", targetNamespace = "")
        java.lang.String dodajKontroleAdres,
        @WebParam(name = "DodajKontrolePojazd", targetNamespace = "")
        java.lang.String dodajKontrolePojazd,
        @WebParam(mode = WebParam.Mode.OUT, name = "DodajKontroleSukces", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> dodajKontroleSukces,
        @WebParam(mode = WebParam.Mode.OUT, name = "DodajKontroleKontrola", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> dodajKontroleKontrola
    );
}
