package pl.eparking.vehicleservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-02-06T20:42:07.185+01:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "VehicleServiceBase", 
                  wsdlLocation = "file:/projects/eparking/workspace/eparking/EparkingServiceRepository/src/main/resources/VehicleService/VehicleServiceBase.wsdl",
                  targetNamespace = "http://eparking.pl/vehicleservice") 
public class VehicleServiceBase_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://eparking.pl/vehicleservice", "VehicleServiceBase");
    public final static QName VehicleServiceBaseSOAP = new QName("http://eparking.pl/vehicleservice", "VehicleServiceBaseSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/projects/eparking/workspace/eparking/EparkingServiceRepository/src/main/resources/VehicleService/VehicleServiceBase.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VehicleServiceBase_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/projects/eparking/workspace/eparking/EparkingServiceRepository/src/main/resources/VehicleService/VehicleServiceBase.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VehicleServiceBase_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VehicleServiceBase_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VehicleServiceBase_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public VehicleServiceBase_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VehicleServiceBase_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VehicleServiceBase_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns VehicleServiceBase
     */
    @WebEndpoint(name = "VehicleServiceBaseSOAP")
    public VehicleServiceBase getVehicleServiceBaseSOAP() {
        return super.getPort(VehicleServiceBaseSOAP, VehicleServiceBase.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VehicleServiceBase
     */
    @WebEndpoint(name = "VehicleServiceBaseSOAP")
    public VehicleServiceBase getVehicleServiceBaseSOAP(WebServiceFeature... features) {
        return super.getPort(VehicleServiceBaseSOAP, VehicleServiceBase.class, features);
    }

}
