package pl.eparking.billservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-02-06T20:42:06.699+01:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://eparking.pl/billservice", name = "BillServiceBase")
@XmlSeeAlso({pl.eparking.base.ObjectFactory.class, ObjectFactory.class, pl.eparking.technical.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BillServiceBase {

    @WebMethod(action = "http://eparking.pl/billservice/rechargeBill")
    @WebResult(name = "rechargeBillResponse", targetNamespace = "http://eparking.pl/billservice", partName = "parameters")
    public RechargeBillResponse rechargeBill(
        @WebParam(partName = "parameters", name = "rechargeBill", targetNamespace = "http://eparking.pl/billservice")
        RechargeBill parameters
    );

    @WebMethod(action = "http://eparking.pl/billservice/getBill")
    @WebResult(name = "getBillResponse", targetNamespace = "http://eparking.pl/billservice", partName = "parameters")
    public GetBillResponse getBill(
        @WebParam(partName = "parameters", name = "getBill", targetNamespace = "http://eparking.pl/billservice")
        GetBill parameters
    );

    @WebMethod(action = "http://eparking.pl/billservice/addBill")
    @WebResult(name = "addBillResponse", targetNamespace = "http://eparking.pl/billservice", partName = "parameters")
    public AddBillResponse addBill(
        @WebParam(partName = "parameters", name = "addBill", targetNamespace = "http://eparking.pl/billservice")
        AddBill parameters
    );

    @WebMethod(action = "http://eparking.pl/billservice/registerBill")
    @WebResult(name = "registerBillResponse", targetNamespace = "http://eparking.pl/billservice", partName = "parameters")
    public RegisterBillResponse registerBill(
        @WebParam(partName = "parameters", name = "registerBill", targetNamespace = "http://eparking.pl/billservice")
        RegisterBill parameters
    );

    @WebMethod(action = "http://eparking.pl/billservice/modifyBill")
    @WebResult(name = "modifyBillResponse", targetNamespace = "http://eparking.pl/billservice", partName = "parameters")
    public ModifyBillResponse modifyBill(
        @WebParam(partName = "parameters", name = "modifyBill", targetNamespace = "http://eparking.pl/billservice")
        ModifyBill parameters
    );
}
