package pl.eparking.accountservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-02-06T20:42:06.510+01:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://eparking.pl/accountservice", name = "AccountServiceBase")
@XmlSeeAlso({ObjectFactory.class, pl.eparking.base.ObjectFactory.class, pl.eparking.technical.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AccountServiceBase {

    @WebMethod(action = "http://eparking.pl/accountservice/findAccount")
    @WebResult(name = "findAccountResponse", targetNamespace = "http://eparking.pl/accountservice", partName = "parameters")
    public FindAccountResponse findAccount(
        @WebParam(partName = "parameters", name = "findAccount", targetNamespace = "http://eparking.pl/accountservice")
        FindAccount parameters
    );

    @WebMethod(action = "http://eparking.pl/accountservice/getAccount")
    @WebResult(name = "getAccountResponse", targetNamespace = "http://eparking.pl/accountservice", partName = "parameters")
    public GetAccountResponse getAccount(
        @WebParam(partName = "parameters", name = "getAccount", targetNamespace = "http://eparking.pl/accountservice")
        GetAccount parameters
    );

    @WebMethod(action = "http://eparking.pl/accountservice/registerAccount")
    @WebResult(name = "registerAccountResponse", targetNamespace = "http://eparking.pl/accountservice", partName = "parameters")
    public RegisterAccountResponse registerAccount(
        @WebParam(partName = "parameters", name = "registerAccount", targetNamespace = "http://eparking.pl/accountservice")
        RegisterAccount parameters
    );

    @WebMethod(action = "http://eparking.pl/accountservice/addAccount")
    @WebResult(name = "addAccountResponse", targetNamespace = "http://eparking.pl/accountservice", partName = "parameters")
    public AddAccountResponse addAccount(
        @WebParam(partName = "parameters", name = "addAccount", targetNamespace = "http://eparking.pl/accountservice")
        AddAccount parameters
    );
}
