package pl.eparking.vehicleservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-02-06T20:44:05.620+01:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://eparking.pl/vehicleservice", name = "VehicleServiceBase")
@XmlSeeAlso({ObjectFactory.class, pl.eparking.base.ObjectFactory.class, pl.eparking.technical.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VehicleServiceBase {

    @WebMethod(action = "http://eparking.pl/vehicleservice/addVehicle")
    @WebResult(name = "addVehicleResponse", targetNamespace = "http://eparking.pl/vehicleservice", partName = "parameters")
    public AddVehicleResponse addVehicle(
        @WebParam(partName = "parameters", name = "addVehicle", targetNamespace = "http://eparking.pl/vehicleservice")
        AddVehicle parameters
    );
}
