<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://eparking.pl/controlservice" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ControlService"
	targetNamespace="http://eparking.pl/controlservice">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://eparking.pl/controlservice"
				schemaLocation="ControlServiceBase.xsd">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="controlParkingRequest">
		<wsdl:part name="parameters" element="tns:controlParking"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="controlParkingResponse">
		<wsdl:part name="parameters" element="tns:controlParkingResponse">
		</wsdl:part>
	</wsdl:message>
	<wsdl:portType name="ControlServiceBase">
		<wsdl:operation name="controlParking">
			<wsdl:input message="tns:controlParkingRequest"></wsdl:input>
			<wsdl:output message="tns:controlParkingResponse"></wsdl:output>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ControlServiceBaseSOAP" type="tns:ControlServiceBase">

		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="controlParking">

			<soap:operation soapAction="http://eparking.pl/controlservice/controlParking" />
			<wsdl:input>

				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>

				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ControlServiceBase">
		<wsdl:port binding="tns:ControlServiceBaseSOAP" name="ControlServiceBaseSOAP">
			<soap:address location="http://eparking.pl/controlservice" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>