package pl.eparking.errorhandlerservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-02-06T20:42:07.292+01:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://eparking.pl/errorhandlerservice", name = "ErrorHandlerService")
@XmlSeeAlso({pl.eparking.technical.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ErrorHandlerService {

    @WebMethod(action = "http://eparking.pl/ErrorHandlerService/handleError")
    @WebResult(name = "handleErrorResponse", targetNamespace = "http://eparking.pl/errorhandlerservice", partName = "parameters")
    public HandleErrorResponse handleError(
        @WebParam(partName = "parameters", name = "handleError", targetNamespace = "http://eparking.pl/errorhandlerservice")
        HandleError parameters
    );
}
