CREATE TABLE `adres` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TYP` varchar(100) NOT NULL,
  `WOJEWODZTWO` varchar(100) NOT NULL,
  `MIEJSCOWOSC` varchar(100) NOT NULL,
  `KOD_POCZTOWY` varchar(100) NOT NULL,
  `ULICA` varchar(100) NOT NULL,
  `NUMER_BUDYNKU` varchar(100) DEFAULT NULL,
  `NUMER_LOKALU` varchar(100) DEFAULT NULL,
  `PIETRO` varchar(100) DEFAULT NULL,
  `OPIS_DODATKOWY` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  UNIQUE KEY `UNIQ_1` (`TYP`,`WOJEWODZTWO`,`MIEJSCOWOSC`,`KOD_POCZTOWY`,`ULICA`,`NUMER_BUDYNKU`,`NUMER_LOKALU`)
) ENGINE=InnoDB AUTO_INCREMENT=17638 DEFAULT CHARSET=utf8;

commit;

CREATE TABLE `kierowca` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `IMIE` varchar(100) DEFAULT NULL,
  `NAZWISKO` varchar(100) DEFAULT NULL,
  `PESEL` varchar(100) NOT NULL,
  `ADRES_EMAIL` varchar(100) NOT NULL,
  `ADRES_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`,`PESEL`,`ADRES_EMAIL`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  UNIQUE KEY `UNIQ_1_PESEL` (`PESEL`),
  UNIQUE KEY `UNIQ_2_EMAIL` (`ADRES_EMAIL`),
  UNIQUE KEY `UNIQ_3` (`IMIE`,`NAZWISKO`,`PESEL`,`ADRES_EMAIL`),
  KEY `KIEROWCA_FK1_idx` (`ADRES_ID`),
  CONSTRAINT `KIEROWCA_FK1` FOREIGN KEY (`ADRES_ID`) REFERENCES `adres` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=17627 DEFAULT CHARSET=utf8;

commit;

CREATE TABLE `pojazd` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TYP` varchar(100) NOT NULL,
  `MARKA` varchar(100) NOT NULL,
  `MODEL` varchar(100) DEFAULT NULL,
  `DATA_PRODUKCJI` date DEFAULT NULL,
  `NUMER_REJESTRACYJNY` varchar(100) NOT NULL,
  `NUMER_VIN` varchar(100) NOT NULL,
  `KOLOR` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  UNIQUE KEY `UNIQ_1_REJ` (`NUMER_REJESTRACYJNY`),
  UNIQUE KEY `UNIQ_2_VIN` (`NUMER_VIN`)
) ENGINE=InnoDB AUTO_INCREMENT=17622 DEFAULT CHARSET=utf8;

commit;

CREATE TABLE `konto` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TYP` varchar(100) NOT NULL,
  `RACHUNEK_ID` varchar(100) NOT NULL,
  `POJAZD_ID` int(11) NOT NULL,
  `KIEROWCA_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  UNIQUE KEY `UNIQ_1` (`TYP`,`RACHUNEK_ID`,`POJAZD_ID`,`KIEROWCA_ID`),
  KEY `KONTO_FK1_idx` (`KIEROWCA_ID`),
  KEY `KONTO_FK2_idx` (`POJAZD_ID`),
  CONSTRAINT `KONTO_FK1` FOREIGN KEY (`KIEROWCA_ID`) REFERENCES `kierowca` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `KONTO_FK2` FOREIGN KEY (`POJAZD_ID`) REFERENCES `pojazd` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=17622 DEFAULT CHARSET=utf8;

commit;

CREATE TABLE `parking` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` varchar(100) NOT NULL,
  `VEHICLE_ID` varchar(100) NOT NULL,
  `PARKING_ID` varchar(100) NOT NULL,
  `PARKING_START` datetime NOT NULL,
  `PARKING_END` datetime DEFAULT NULL,
  `PARKING_TYPE` varchar(100) NOT NULL,
  `PARKING_STATUS` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  UNIQUE KEY `UNIQ_1_ID` (`PARKING_ID`,`ACCOUNT_ID`,`VEHICLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

commit;
