package pl.eparking.controlservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-02-06T20:44:05.246+01:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "ControlServiceBase", 
                  wsdlLocation = "file:/projects/eparking/workspace/eparking/EparkingServiceRepository/src/main/resources/ControlService/ControlServiceBase.wsdl",
                  targetNamespace = "http://eparking.pl/controlservice") 
public class ControlServiceBase_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://eparking.pl/controlservice", "ControlServiceBase");
    public final static QName ControlServiceBaseSOAP = new QName("http://eparking.pl/controlservice", "ControlServiceBaseSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/projects/eparking/workspace/eparking/EparkingServiceRepository/src/main/resources/ControlService/ControlServiceBase.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ControlServiceBase_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/projects/eparking/workspace/eparking/EparkingServiceRepository/src/main/resources/ControlService/ControlServiceBase.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ControlServiceBase_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ControlServiceBase_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControlServiceBase_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ControlServiceBase_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ControlServiceBase_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ControlServiceBase_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ControlServiceBase
     */
    @WebEndpoint(name = "ControlServiceBaseSOAP")
    public ControlServiceBase getControlServiceBaseSOAP() {
        return super.getPort(ControlServiceBaseSOAP, ControlServiceBase.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControlServiceBase
     */
    @WebEndpoint(name = "ControlServiceBaseSOAP")
    public ControlServiceBase getControlServiceBaseSOAP(WebServiceFeature... features) {
        return super.getPort(ControlServiceBaseSOAP, ControlServiceBase.class, features);
    }

}
